# renew_before_expiry = 30 days
version = 3.2.0
archive_dir = /etc/letsencrypt/archive/ontheflyai.ru
cert = /etc/letsencrypt/live/ontheflyai.ru/cert.pem
privkey = /etc/letsencrypt/live/ontheflyai.ru/privkey.pem
chain = /etc/letsencrypt/live/ontheflyai.ru/chain.pem
fullchain = /etc/letsencrypt/live/ontheflyai.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 93d2394a233a1cf7acedb2950ce737ce
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
