version: "3.8"

services:
  bookworm-agent:
    build: .
    container_name: bookworm-agent
    ports:
      - "7860:7860"
    network_mode: bridge

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html  # <== Добавляем проброс директории
    depends_on:
      - bookworm-agent
    network_mode: bridge

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html  # <== Проброс для certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email rakhmanov-v@ya.ru --agree-tos --no-eff-email -d ontheflyai.ru