version: "3.8"
services:
  bookworm_app:  # <-- Задаем название контейнера с твоим приложением
    build: .
    container_name: bookworm_app  # <-- Явное имя контейнера
    ports:
      - "7860:7860"
    depends_on:
      - ollama
      - chroma
      - meilisearch
    networks:
      - mynetwork

  ollama:
    image: ollama/ollama:0.5.12
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - mynetwork

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: "e9a9e2fa957d9c681ff3bb53f919f2b5"
    ports:
      - "7700:7700"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge