version: "3.8"
services:
  bookworm-agent:
    build: .
    container_name: bookworm-agent
    ports:
      - "7860:7860"
    networks:
      - bookworm_network  # Используем свою сеть

networks:
  bookworm_network:  # Создаем свою сеть
    driver: bridge