use_default_settings: true

general:
  instance_name: "bookworm-searxng"

server:
  secret_key: "%(ENV_SEARXNG_SECRET)s"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
